[package]
name = "archiver"
version = "0.1.0"
authors = ["Konstantin Ilchenko <kyle.mom.is.awesome@gmail.com>"]

[dependencies]
hyper = "^0.8.0"
iron = { version = "^0.3.0", features = ["ssl"] }
router = "^0.1.1"
logger = "^0.0.3"
regex = "^0.1.60"
config = "^0.1.0"
unicase = "^1.4.0"